spring.application.name=ecommerce
spring.output.ansi.enabled=ALWAYS
server.port=5454

#db specific properties
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}


#ORM s/w specific properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//razorpay.api.key=rzp_test_S5lFSBzEJ0PBTB
//razorpay.api.secret=b5KyVcjIsecUAgvMErkNKbie
razorpay.api.key=b5KyVcjIsecUAgvMErkNKbie
razorpay.api.secret=S4tQC0tgFaV7y8


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=vishalgon45@gmail.com
spring.mail.password=yxpliiinfrarxgng

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true